image:
    file: .gitpod.Dockerfile

tasks:
    - before: |
          mkdir -p /workspace/.caches/pre-commit
          ln -s /workspace/.caches/pre-commit  ~/.cache/pre-commit
      init: |
          ./scripts/init_env.sh -i
          pre-commit install --install-hooks
          gp preview file://$GITPOD_REPO_ROOT/docs/_build/html/index.html
      command: |
          pip install -e $GITPOD_REPO_ROOT[cpp]

github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
        # enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
        # add a check to pull requests (defaults to true)
        addCheck: true
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: true
        # add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: false
        # add a label once the prebuild is ready to pull requests (defaults to false)
        addLabel: false
