#!/bin/bash

set -e

REPO_ROOT=$(dirname $(dirname "$(readlink -e $0)"))

echo -e "\nComputing requirements ..."

/usr/bin/env python3 -c "\
import configparser; \
c = configparser.ConfigParser(); \
c.read('setup.cfg'); \
print(c['options']['install_requires']); \
print(c['options.extras_require']['cpp'])"  > $REPO_ROOT/.requirements_min.tmp

pip-compile --no-header -o $REPO_ROOT/.requirements_fixed.tmp $REPO_ROOT/.requirements_min.tmp $REPO_ROOT/requirements_dev.txt

cat > $REPO_ROOT/requirements_fixed.txt << EOT
#
# This file is autogenerated by the script: REPO_ROOT/scripts/update_requirements.sh
# Run the script again to update the packages in this list.
#
EOT

cat $REPO_ROOT/.requirements_fixed.tmp >> $REPO_ROOT/requirements_fixed.txt
rm $REPO_ROOT/.requirements_min.tmp $REPO_ROOT/.requirements_fixed.tmp

cat << EOT

Updated ${REPO_ROOT}/requirements_fixed.txt file.
To install exactly these packages in your virtual environment run:

    pip-sync ${REPO_ROOT}/requirements_fixed.txt

or

    pip install --force-reinstall -r ${REPO_ROOT}/requirements_fixed.txt

EOT
