#!/bin/bash

set -e

EVE_ROOT=$(dirname $(dirname "$(readlink -e $0)"))

/usr/bin/env python3 -c "\
import configparser; \
c = configparser.ConfigParser(); \
c.read('setup.cfg'); \
print(c['options']['install_requires']); \
print(c['options.extras_require']['cpp'])"  > $EVE_ROOT/requirements.in

pip-compile --no-header -o $EVE_ROOT/.requirements_all.tmp $EVE_ROOT/requirements.in $EVE_ROOT/requirements_dev.in

cat > $EVE_ROOT/requirements_all.txt << EOT
#
# This file is autogenerated by the script: ${EVE_ROOT}/scripts/update_requirements.sh
# Run the script again to update the packages in this list.
#
EOT

cat $EVE_ROOT/.requirements_all.tmp >> $EVE_ROOT/requirements_all.txt
rm $EVE_ROOT/.requirements_all.tmp

cat << EOT

Updated ${EVE_ROOT}/requirements_all.txt file.
To install the new-packages in your virtual environment run:

    pip-sync ${EVE_ROOT}/requirements_all.txt

or

    pip install --force-reinstall -r ${EVE_ROOT}/requirements_all.txt

EOT
